fyl_try2/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.defaults import handler404, handler500


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fyl_try2.views.home', name='home'),
    # url(r'^fyl_try2/', include('fyl_try2.foo.urls')),
    
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', 'fyl_try2.views.index'),
    url(r'^faq$', 'fyl_try2.views.faq', name='faq'),
    url(r'^about$', 'fyl_try2.views.about', name='about'),
#    url(r'^contact$', 'fyl_try2.views.contact', name='contact'),
    url(r'^us-congress$', 'fyl_try2.views.get_us_congress', name='us-congress'),
    url(r'^political-map$', 'fyl_try2.views.us_congress_pltcl_map', name='us-congress-map'),
    url(r'^us-congress/trends$', 'fyl_try2.views.us_congress_trends', name='us-congress-trends'),
    url(r'^ngrams$', 'fyl_try2.views.us_congress_trends', name='us-congress-trends'),
   
)
handler404 = 'fyl_try2.views.custom_404_view'
#handler500 = 'fyl_try2.views.custom_404_view'

fyl_try2/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(max_length=100)
	email = forms.EmailField(required=False, label='Your e-mail address')
	message = forms.CharField(widget=forms.Textarea)

fyl_try2/views.py
from django.http import HttpResponse
from django.template import loader
from django.core.mail import send_mail
from django.template.context import Context
from django.core.context_processors import request
from django.db import connection, transaction
from fyl_try2.forms import ContactForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.serializers.json import DjangoJSONEncoder
import json



def index(request):
    return get_us_congress(request)
#    cursor = connection.cursor()
#    cursor.execute("SELECT tweet_text from tweets order by tweet_id  desc limit 5")
#    row = cursor.fetchall()
#    print row
#    
#    t = loader.get_template('index.html')
#    c = Context({'row':row})
# #    c = Context({})
#    return HttpResponse(t.render(c))
#    pass

def faq(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['name'],
                cd['message'],
                cd.get('email', 'noreply@fyl_faq.com'),
                ['info@followyourleaders.org'],
            )
            return HttpResponseRedirect('/faq')
    else:
        form = ContactForm()  # An unbound form
        
    t = loader.get_template('faq.html')
    c = Context({'form': form, })
    return HttpResponse(t.render(c))
    pass

# ----  Not Implemented
def contact(request):
    t = loader.get_template('contact.html')
    c = Context({})
    return HttpResponse(t.render(c))
    pass

def about(request):
    t = loader.get_template('about.html')
    c = Context({})
    return HttpResponse(t.render(c))
    pass

def custom_404_view(request):
    t = loader.get_template('404.html')
    c = Context({})
    return HttpResponse(t.render(c))
    pass

def get_recent_tweet():
    cursor = connection.cursor()
    cursor.execute("SELECT tweet_text from tweets order by tweet_id  desc limit 1")
    row = cursor.fetchone()
    print "Row is: " + row
    return HttpResponse (json.dumps(row), mimetype="application/json")
    
def get_us_congress(request): 
    cursor = connection.cursor()
    query = '''
		SELECT created_at,name,tweet_text,image_url,screen_name,tweet_url,location, geo_lat, geo_long  FROM 
		(SELECT * from TwitterCollector.tweets  where tweets.user_id in (Select user_id from TwitterCollector_113thCongress.user_list ) order by tweet_id  desc limit 500) as tweets,
		TwitterCollector.user_info as user_info
		where 
		tweets.user_id= user_info.user_id
		group by name
		order by tweet_id  desc limit 20;'''
    print "Query: "+query   
    cursor.execute(query)
    # cursor.execute("SELECT tweet_text from tweets order by tweet_id  desc limit 5")
    row = cursor.fetchall()

    t = loader.get_template('us-congress.html')
    c = Context({'row':row, })
    return HttpResponse(t.render(c))

def us_congress_pltcl_map(request):
    cursor = connection.cursor()
    query = '''
		SELECT created_at,name,tweet_text,image_url,screen_name,tweet_url,location, geo_lat, geo_long  FROM 
		(SELECT * from TwitterCollector.tweets where tweets.user_id in (Select user_id from TwitterCollector_113thCongress.user_list ) order by tweet_id  desc limit 5000) as tweets,
		TwitterCollector.user_info as user_info
		where 
		tweets.user_id= user_info.user_id
		and tweets.geo_lat != 0
		group by name
		order by tweet_id  desc limit 500;'''
    cursor.execute(query)
    congressTweets = cursor.fetchall()
    congressTArray = list(congressTweets)  # convert to Array from tuple
    for i in range(0, len(congressTArray)):
        congressTArray[i] = list(congressTArray[i])
        congressTArray[i][0] = str(congressTArray[i][0])  # date time format fixes
    congressArray = json.dumps(congressTArray, cls=DjangoJSONEncoder);
    print congressArray
#    print type( congressTweets)

    t = loader.get_template('political-map.html')
    c = Context({'congressArray':congressArray, })
    return HttpResponse(t.render(c))
	
def us_congress_trends(request):
    trendsArray = [];
    trendValue = "";
    recommended=["Bailout","Boston"];
    recent=["Gun Control","Boston Marathon"];
    
    if (request.method and request.method == 'GET'):
        print "inside the get method"    
        if 'trend' in request.GET:
            trendValue = request.GET['trend']
            cursor = connection.cursor()
            print 3 * '$$$$'
            print trendValue
            query = '''
				SELECT name,count(name)  FROM 
				(SELECT * from TwitterCollector.tweets where  tweets.tweet_text like %s  and tweets.user_id in (Select user_id from TwitterCollector_113thCongress.user_list ) order by tweet_id  ) as tweets,
				TwitterCollector.user_info as user_info
				where 
				tweets.user_id= user_info.user_id
				group by name
				order by count(name)  desc limit 15;'''
            args = ('%' + trendValue + '%')
            print "Query: "+query
            cursor.execute(query, args)
            tempArray = cursor.fetchall()
            print 3 * '$$$$'
            temp = [[], []]
#           print trendsArray
            trendsArray = list(tempArray)
            temp = [[row[i] for row in trendsArray] 
                        for i in range(2)]
#           temp=zip(*tempArray)
#           print temp
            trendsArray = json.dumps(temp, cls=DjangoJSONEncoder)
            print tempArray
        else:
            trendsArray = [];
        
    
    t = loader.get_template('trends.html')
    c = Context({'trendsArray':trendsArray, 'trendValue':trendValue, 'recommended':recommended, 
                 'recent':recent})
    return HttpResponse(t.render(c))

	
# util functions --to be moved into seperate class

	
def convert_tuple_array(tuple):
    tupleArray = list(tuple)  # convert to Array from tuple
    for i in range(0, len(tupleArray)):
        tupleArray[i] = list(tupleArray[i])

#    tupleArray = json.dumps(tupleArray, cls=DjangoJSONEncoder);
    return tupleArray;

fyl_try2/templates/about.html
{% extends "base.html" %}
{% block title %} About {% endblock %}

{% block content %}

<div class="page-header" align="center">

	<h1>About <small>Follow Your Leaders</small></h1>

</div>
<div class="page-content">
<!-- <div class="container"> -->
	<p>
		Follow Your Leaders is part of a larger research project about politicians and <a href="http://casmlab.org/projects/publicofficials/" target="_blank"> social media </a> from the Collaboration and <a href="http://www.casmlab.org">Social Media Lab </a> at the <a href="http://www.iit.edu">Illinois Institute of Technology</a>. The goal of the website is to allow users to explore data from Twitter and other sources to see how politicians use social media. You can read more about our research at the <a href="http://casmlab.org/projects/publicofficials/" target="_blank">CaSM Lab website</a>.
	</p>

	<!--
	><h3 id="system_architecture">System Architecture</h3>
	[need Yazan to describe collector]
	[devs a blurb about how the website works]
	-->

	<h3 id="principal_investigators">Principal Investigators</h3>
	<ul>
		<li><a href="http://www.libbyh.com" target="_blank">Libby Hemphill</a></li>
		<li><a href="http://lincs.hum.iit.edu/?q=content/jahna-otterbacher" target="_blank">Jahna Otterbacher</a></li>
		<li>Matthew A. Shapiro</li>
	</ul>

	<h3 id="web_design_and_development">Web Design and Development</h3>
	<ul>
		<li>Eyoel Asfaw</li>
		<li>Subhi Beidas</li>
		<li>Yazan Hussein</li>
		<li>Ruth Zinsmeister</li>
	</ul>
</div>
{% endblock %}

fyl_try2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="utf-8">
		<title>Follow Your Leaders | {% block title %} Home {% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Le styles -->
		<link href="{{MEDIA_ROOT}}media/bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="{{MEDIA_ROOT}}media/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		<link href="{{MEDIA_ROOT}}media/bootstrap/css/overrides.css" rel="stylesheet">

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<script src="{{MEDIA_ROOT}}media/bootstrap/js/jquery-1.8.1.min.js" type="text/javascript"></script>
		<script src="{{MEDIA_ROOT}}media/bootstrap/js/bootstrap-modal.js" type="text/javascript"></script>
		<script src="{{MEDIA_ROOT}}media/bootstrap/js/bootstrap-dropdown.js" type="text/javascript"></script>
		<link href="{{MEDIA_ROOT}}media/css/base.css" rel="stylesheet">
		{% block links %}
		{% endblock %}
		{% block extrahead %}
		{% endblock %}
		<script type="text/javascript">
			
				{% block javascript %}
				{% endblock %}
			
		</script>
	</head>

	<body>
		 <div id="wrap">
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<!-- <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar">c</span> <span class="icon-bar">d</span> <span class="icon-bar">x</span> </a> -->
					<a class="brand" href="{% url fyl_try2.views.index %}">Follow Your Leaders </a>
					 {% block navbar_title %} {% endblock %}
					<!-- <div style="float:right;">
						
						<form class="navbar-search">
							<input type="text" class="search-query span3" placeholder="Search">
						</form>
					</div> -->
					<div class="nav-list" style="float:right;">
						<ul class="nav">
							<li class="dropdown">
								<a href="" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" style="color: #FFCC9F"> Key Links <b class="caret"></b> </a>
								<ul class="dropdown-menu">
									<li>
										<a tabindex="0" href="{% url fyl_try2.views.get_us_congress %}" style="color: #FFCC9F">US Congress</a>
									</li>
									<li class="divider"></li>
									<li>
										<a tabindex="1" href="#" style="color: #FFCC9F">Korean National Assembly</a>
									</li>
									<li>
										<a tabindex="2" href="#" style="color: #FFCC9F">EU Parliament</a>
									</li>
									
								</ul>
							</li>
							<li class="active">
								<a href="{% url fyl_try2.views.faq %}" style="color: #FFCC9F">FAQ</a>
							</li>
							<li>
								<a href="{% url fyl_try2.views.about %}" style="color: #FFCC9F">About</a>
							</li>
						</ul>

					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>
		<div class="container">
		{% block content %}{% endblock %}
		</div>
		<div id="push"></div>
	</div>	
	
	<div class="footer" id="footer">
	      <div class="container">
        <p class="muted credit">Product of <a href="http://libbyh.com" target="_blank">Libby Hemphill</a> and <a href="http://casmlab.org" target="_blank">CaSM Lab </a>.</p>
      </div>
     </div>
	</body>
</html>

fyl_try2/templates/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Follow Your Leaders | {% block title %}Contact{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/media/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/media/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="/media/bootstrap/js/jquery-1.8.1.min.js" type="text/javascript"></script>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar">c</span>
            <span class="icon-bar">d</span>
            <span class="icon-bar">x</span>
          </a>
          <a class="brand" href="/">Follow Your Leaders</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            
            <div>
            	<form class="navbar-search">
               		<input type="text" class="search-query span3" placeholder="Search">
            	</form>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
This is contact
  </body>
</html>

fyl_try2/templates/faq.html
{% extends "base.html" %}
{% block title %} FAQ {% endblock %}

{% block content %}

<div class="page-header" align="center">
  <h1>Frequently Asked Questions</h1>
</div>
<div class="page-content">
	Don't see the answer to your question? Click <strong> <a href="#faq_form" data-toggle="modal"> here </a></strong> to send your question to us.
	<br><!-- {{ form.non_field_errors }} {{ form.subject.errors }} -->
	<br>

		<h3 id="what_is_follow_your_leaders?">What is Follow Your Leaders?</h3>
	<p>	Follow Your Leaders is the website for a research project that helps you see how elected officials use social media, especially Twitter. We collect tweets from Twitter and combine them with data from other sources like roll call votes, fundraising efforts, and the Census to show trends and differences in how politicians use social media.</p>

		<h3 id="how_do_you_get_the_data?">How do you get the data?</h3>
		<p>We've been collecting data since the summer of 2011 using the <a href="https://dev.twitter.com/docs/streaming-apis" target="_blank">Twitter Streaming API</a>. We currently use a <a href="http://www.python.org/" target="_blank">Python</a> application to retrieve data from Twitter, parse the data, and store it in <a href="http://www.mysql.com/" target="_blank">MySQL</a> databases. The code for <a href="https://github.com/casmlab/pyTwitterCollector" target="_blank">our latest collector application</a> is available on Github.</p>
	<br>
		We also pull data from other public sources including
		<ul>
		<li><a href="http://www.congress.org" target="_blank">Congress.org</a></li>
		<li><a href="http://www.govtrack.us" target="_blank">govtrack.us</a></li>
		<li><a href="http://www.voteview.com" target="_blank">Voteview.com</a></li>
		</ul>

		<h3 id="how_can_i_find_politicians_on_twitter?">How can I find politicians on Twitter?</h3>
		We curate lists for the following groups of leaders:
		<ul>
		<li><a href="https://twitter.com/CaSMLab/u-s-house-of-reps-113th/members" target="_blank">U.S. House of Representatives</a></li>
		<li><a href="https://twitter.com/CaSMLab/u-s-senate-113th/members" target="_blank">U.S. Senate</a></li>
		<li><a href="https://twitter.com/CaSMLab/eu-parliament/members" target="_blank">European Parliament</a></li>
		<li><a href="https://twitter.com/CaSMLab/korea/members" target="_blank">National Assembly of the Republic of Korea</a></li>
		<li><a href="https://twitter.com/CaSMLab/chicago-aldermen/members" target="_blank">Chicago City Council</a></li>
		</ul>

	<h3 id="what_is_an_n-gram?">What is an n-gram?</h3>	
	<p>Technially, an n-gram is a contiguous sequence of n items from a given snippet of text or speech. For our purposes, n-grams are words or phrases that appear in tweets, such as "Obamacare" (a 1-gram) or "tax hike" (a 2-gram). The n-gram viewer shows how often that n-gram appears in our dataset, or in the subset you've selected, over time.
	</p>
</div>
	
<div class="modal hide fade" id="faq_form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" data-bind="click: cancel">&times;</button>
        <h3>What's your Question</h3>
    </div>
    <div class="modal-body">
        <form action="" data-bind="submit: add" method="post">
			<label class="control-label" for="id_name">Name*:</label>
            		{{ form.name }}
            <label class="control-label" for="id_email">Email*:</label>
            		{{ form.email }}            
            <div class="control-group">
                <label class="control-label" for="id_message">Questions*:</label>
                <div class="controls">
                    {{ form.message }}
                </div>
            </div>


        </form>
    </div>
    <div class="modal-footer">
        <a href="" class="btn btn-primary" data-bind="click: add">Submit Questions</a>
        <a href="#" class="btn" data-dismiss="modal" data-bind="click: cancel">Cancel</a>
    </div>
</div>

{% endblock %}

fyl_try2/templates/index.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block content %}
<div style="color: #333333; margin-bottom:5%;" class="container-fluid " id="homepage_header">
	<h1> Follow Your Leaders</h1>

	<!-- <div style="float: left;" class="container-fluid ">
	<canvas  id="arrow"></canvas>
	</div> -->
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span9">
			<div style=" color: #FF9900; ">
				<div class="span6 offset4" id="main_menu_options" style="margin-top: 15%;">
					<a style="color: #FF9900"href="/us-congress" ><label  style="font-size: 24px;">US Congress</label></a>
					<a style="color: #FF9900"href="/" ><label style="font-size: 24px;">Korean National Assembly</label></a>
					<a style="color: #FF9900"href="/" ><label style="font-size: 24px;">EU Parliament</label></a>
				</div>
			</div>
		</div>
		<div class="span3" style="border: 1px solid #f5f5f5;
				color: #FF9900;
				background-color: #FFCC9F;">
			<h4>Recent Updates</h4>

			{% for r in row %}
			<div align="center">
				{{r}}
			</div>
			{% endfor %}
		</div>

	</div>
</div>

{% endblock %}

fyl_try2/templates/political-map.html
{% extends "us-congress.html" %}

{% block title %} US Congress {% endblock %}

{% block congress-links %}
<link href="{{MEDIA_ROOT}}media/css/political-map.css" rel="stylesheet">
<script src="{{MEDIA_ROOT}}media/js/political-map.js" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" type="text/javascript"></script>
<script>
	var tweetData={{congressArray|safe}};
	var map;
	google.maps.event.addDomListener(window, 'load', initialize); 
</script>
{% endblock %}
{% block javascript %}
{% endblock %}


{% block congress_body %}
<div class="page-header" align="center" id="political-maps">
	<h1>Political Maps</h1>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="well-large">
			<div class="span10 offset1">
				<div id="map-canvas"></div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

fyl_try2/templates/trends.html
{% extends "us-congress.html" %}

{% block title %} US Congress Trends {% endblock %}

{% block congress-links %}
<link href="{{MEDIA_ROOT}}media/css/trends.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<script>
	var tweetData ={{trendsArray|safe}};
	var trendValue = "{{trendValue}}";
</script>
<script src="{{MEDIA_ROOT}}media/js/trends.js" type="text/javascript"></script>
{% endblock %}
{% block javascript %}

{% endblock %}

{% block congress_body %}

<div class="page-header" align="center" id="political-maps">
	<h1>Trends <small>What's all the chatter?</small</h1>
</div> 
<div class="container-fluid" id="trends_intro" style="text-align: center;">
	<p id="intro_to_trends">
		Wonder what the politicians are talking about? Do they spend more time talking about Bieber than tax law? Search any topic and time to see what drew the tweets from the representatives.
	</p>
</div>
<div style="alignment-adjust: center;">
	<form action="">
		<p id="formlabel">Phrase Search        </span><input name="trend" type="text" placeholder="ex golf, voting, gun control">
		<button type="submit" class="btn btn-warning" id="search_button">
			Search
		</button></p>
	</form>
</div>
<hr>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span4" id="trend_recommendations">
			<div class="row-fluid">
				<h3>Recommended Topics</h3>
				<br>
				{% for r in recommended %}
				<span></spand><a href="{% url fyl_try2.views.us_congress_trends %}?trend={{r}}">{{r}}</a></span>
				<br>
				{% endfor %}
				<br>
			</div>
			<div class="row-fluid">
				<h3>Recent Searches</h3>
				<br>
				{% for r in recent %}
				<span></spand><a href="{% url fyl_try2.views.us_congress_trends %}?trend={{r}}">{{r}}</a></span>
				<br>
				{% endfor %}
				<br>
			</div>
		</div>
			<div class="span8">
				<div id="trends-canvas" style="min-height: 500px; width: 100%; margin: 0 auto"></div>
			</div>

	</div>
</div>

{% endblock %}

fyl_try2/templates/us-congress.html
{% extends "base.html" %}
{% block title %} US Congress {% endblock %}

{% block links %}
{% load staticfiles %}
<link href="{{MEDIA_ROOT}}media/css/us-congress.css" rel="stylesheet">
<script src="{{MEDIA_ROOT}}media/css/overrides.css" type="text/javascript"></script>
{% block congress-links %}
<script src="{{MEDIA_ROOT}}media/js/recent-tweets.js" type="text/javascript"></script>
<link href="{{MEDIA_ROOT}}media/css/recent-tweets.css" rel="stylesheet">
{% endblock %}
{% endblock %}
{% block javascript %}
max= {{ row|length }};
{% endblock %}

{% block navbar_title %} <a class="brand" href="{% url fyl_try2.views.get_us_congress %}" style="color: #FFCC9F;font-size: 15px;">US Congress</a> {% endblock %}

{% block content %}
{% block congress_body %}
<div class="page-header" align="center">
	<h1>US Congress</h1>
</div>

<div class="container-fluid">
	<div class="row-fluid">
		<div align="center">
			<h4> Recent Tweets </h4>
		</div>

		<div id="tweetbox" class="span8 offset2">
			{% for r in row %}

			<div id="container">
				<div id="example" class="tweets">
					<div class="tweet tweet-{{r.0}}" id="tweet-{{forloop.counter}}" style="display:none;">
						<img width="40" height="40" src={{r.3}}>
						<p class="text">
							<span class="username"><a href="http://twitter.com/#!/{{r.4}}" target="_blank">{{r.1}}</a>:</span> {{r.2}} <span class="time"><a href="{{r.5}}" target="_blank"> {{r.0}} </a></span>
						</p>
					</div>
				</div>
			</div>
			{% endfor %}
			
		</div>
	</div>
	{% endblock %}
	<br>
 
	<div class="row-fluid">
		<div class="span4">
			<div id="public-maps" class="well-large">
				<h3>Public</h3>
				<span><a href="{% url fyl_try2.views.us_congress_pltcl_map %}">Political Map</a></span>
				<br>
				Network Map
				<br>
				Congress Map
				<br>
			</div>

		</div>
		<div class="span4">
			<div id="centerdiv" class="well-large">
				<br><br>
				Find Your Representative
				<br>
				<span><a href="{% url fyl_try2.views.us_congress_trends %}?trend=boston">Trends</a></span>
				<br>
				Networks
				<br>
			</div>

		</div>
		<div class="span4">
			<div id="public-maps" class="well-large">
				<h3>Research</h3>
				Data Retrieved
				<br>
				Request Information
				<br>
			</div>
		</div>
	</div>


{% endblock %}